name: Exécuter le script à 19h30

on:
  schedule:
      - cron: '25 17 * * *'  # Exécute tous les jours à 17h30 UTC (19h30 heure de Paris en heure d'été)
  workflow_dispatch:     # Permet de lancer manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris  # Définit le fuseau horaire à Paris

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Exécuter le script
        env:
          MAIL: ${{ secrets.MAIL }}
          MDP: ${{ secrets.MDP }}
          DISCORD: ${{ secrets.DISCORD }}
          MAILE: ${{ secrets.MAIL }}
          MDPE: ${{ secrets.MDP }}

        run: |
          python reza.py
